name: DB Build Tests

on:
  push:
    branches: [main]
    paths:
      - "packages/db_build/**"
      - ".github/workflows/db-build-tests.yml"
  pull_request:
    branches: [main]
    paths:
      - "packages/db-build/**"
      - ".github/workflows/db-build-tests.yml"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.12", "3.13", "3.14"]

    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/cache@v4
        with:
          path: .git/lfs
          key: lfs-${{ hashFiles('.lfsconfig') }}-${{ hashFiles('**/*.bson') }}
          restore-keys: lfs-

      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --all-packages

      - name: Run tests
        working-directory: .
        run: uv run pytest ./packages/db_build/tests/ -v
